jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image (classic build)
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/windows-devbox:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/windows-devbox:latest