name: Build and Push Windows Dev Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - Dockerfile
      - docker-bake.hcl
      - .github/workflows/docker-build-windows.yml

jobs:
  build-and-push:
    runs-on: windows-2022  # Requires Windows runner

    env:
      IMAGE_NAME: windows-devbox

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image using bake
        run: |
          docker buildx bake --push --set *.platform=windows/amd64 --set *.tags=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
