name: Build and Push Windows Dev Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - Dockerfile
      - .github/workflows/docker-build-windows.yml

jobs:
  build:
    runs-on: windows-2022

    env:
      IMAGE_NAME: windows-devbox

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest .

      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest